### PR TITLE
MLDB-1354 merge unpack_json into parse_json

### PR DESCRIPTION
**Pull request by steadtler**
NK will update the doc afterwards.

### CODE REVIEW

**Comment by mailletf** [comment]
Since this is breaking production deployments, I vote for a brief period where the old function name still works and is marked as deprecated, so there can be a smooth switch over.

**Comment by nicolaskruchten** [comment]
DOD updated.

**Comment by nicolaskruchten** [comment]
@steadtler can you add the `unpack_json` code back in plz? I'll add the documentation commit to this branch.

**Comment by nicolaskruchten** [comment]
+1

**Pull request merged**
