### PR TITLE
[MLDB-1547] added validation of modelFileUrl when functionName is spe…

### PR DESCRIPTION
**Pull request by guyd**
- added the validation to all procedure that can generate a function pointing to a model.  When the modelFileUrl is invalid or not specified, the creation of the procedure will fail
- simplified the config validation code to use variadic template and remove the use of template where it was providing little value
- moved the name of a procedure (e.g kmeans.train) to its config declaration so that we can reuse it easily

### CODE REVIEW

**Comment by steadtler** [comment]
The high number of changes might make the upcoming refactoring difficult to integrate

**Comment by guyd** [comment]
I will wait until the row and column naming changes are in.

**Comment by nicolaskruchten** [comment]
The big changes have hit master, we can finish this one up now :)

**Comment by steadtler** [comment]
+1

**Pull request merged**
