### PR TITLE
Mldb 1771 cls categorial weighting

### PR DESCRIPTION
**Pull request by mailletf**

### CODE REVIEW

**Comment by jeremybarnes** [comment]
Why did the mldb-961 test results change?

**Comment by mailletf** [comment]
What I'm thinking is that it's because the weighting of the classes has changed, leading to a different weighting for each example, leading to a slightly different model.

**Comment by jeremybarnes** [comment]
Why did the weighting of the classes change?  If it was due to a bug fix, good.  I can't see if this was an expected change or not.

**Comment by mailletf** [comment]
That's the PR. Before it was only weighting labels True/False. It was hardcoded for boolean. Now, if it's categorical, it does more than 2. Since the glz test was on iris and there are 3 classes, the 3rd one used to not get weighted and now it does.

**Comment by jeremybarnes** [comment]
+1

**Pull request merged**
