### PR TITLE
MLDB-1058: "getResponseReasonPhrase" now returns a const string ref

### PR DESCRIPTION
**Pull request by wsourdeau**
This change enables a single instantiation of std::string per reason code, in order to reduce the number of allocations taking place during the returning of an HTTP response.

### CODE REVIEW

**Comment by jeremybarnes** [comment]
What is the rationale?  You should put one in the description.

Also, why not return a const char * from the function?

**Comment by wsourdeau** [comment]
@jeremybarnes for the "const char *": because it's more idiomatic and safer. Technically, "const char *" can be freed without a compiler warning.

**Comment by wsourdeau** [comment]
@jeremybarnes descriptoin amended.

**Comment by jeremybarnes** [comment]
If you free a const char * from read-only memory where these strings come from, you will get a crash instantly.

The change is OK, I guess, but it's bigger than it needs to be and I really don't see the need for the static initialization everywhere.

+1 anyway.

**Comment by nicolaskruchten** [comment]
What is the performance improvement from this PR?

**Comment by wsourdeau** [comment]
@nicolaskruchten 2 kqps
I am still recovering the hair I've lost by benchmarking this.

**Comment by nicolaskruchten** [comment]
ok. please merge, you already have a +1 from Jeremy

**Pull request closed without merging**
