### PR TITLE
MLDB-1884 fix null default ts

### PR DESCRIPTION
**Pull request by FinchPowers**

### CODE REVIEW

**Comment by steadtler** [comment]
+1 when tests pass

**Comment by jeremybarnes** [comment]
Rationale for it being negative infinity versus notADate()?

**Comment by FinchPowers** [comment]
My current task was limited to making the results consistent with the other "NULL" examples.

```
SELECT 'patate' -> "-Inf"
SELECT NULL LIKE 'abc' -> "-Inf"
```

The current patch makes it so that
```
SELECT NULL -> "-Inf"
```
instead of 1970-...


If we want to make it "not a date" then every where we have -Inf should be updated too and it should be done in a separate task.

**Comment by jeremybarnes** [comment]
OK, I agree that it's better than the previous version.  +1

**Pull request merged**
