### PR TITLE
mldb_logger.py - force utf8 decoding of input lines

### PR DESCRIPTION
**Pull request by jraby**

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Is this related to the verbal bug report I made yesterday?

**Comment by jraby** [comment]
yes.  this is incomplete for now, passing invalid codepoints will throw

**Comment by jraby** [comment]
Invalid code points are now replaced:

```
<html><body>
<pre>2016-03-03T18:34:41.174861Z    these are invalid points: ���
2016-03-03T18:34:41.174971Z
2016-03-03T18:34:42.046251Z    these are invalid points: ���
2016-03-03T18:34:42.046375Z
2016-03-03T18:34:43.048107Z    these are invalid points: ���
...
```

**Comment by nicolaskruchten** [comment]
+1

i'll report back with a JIRA issue if I can still replicate the initial bug.

**Pull request merged**
