### PR TITLE
bump jdcal to 1.0.1 because 1.0 no longer available

### PR DESCRIPTION
**Pull request by co-dh**

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
@jraby are we shielded from this sort of problem on khan because of the wheelhouse?

**Comment by jraby** [comment]
Yes.

**Comment by nicolaskruchten** [comment]
@jraby should we accept this PR? What else is required? You need to add the new version to the wheelhouse etc? Rebuild mldb_base?

**Comment by jraby** [comment]
Once this is in, we need to add the package to the wheelhouse and rebuild mldb_base.

However, I think we should upgrade to the latest version (1.2)  instead of 1.0.1, unless there's some compatibility issue.

**Comment by co-dh** [comment]
There should be no according to there change log.
somebody need to make sure the unit test covers this package well, and then
run the unit test.

**Comment by nicolaskruchten** [comment]
Where does this dep come from? Jupyter?

**Comment by jraby** [comment]
jdcal comes from openpyxl:

```
Collecting jdcal (from openpyxl==2.2.6->-r /home/jean/ws/src/mldbpro/python_requirements.txt (line 14))
  Downloading jdcal-1.2.tar.gz
```

I will update it to 1.2

**Comment by jraby** [comment]
Closing, I will use 1.2.

**Pull request closed without merging**
