### PR TITLE
[MLDB-1506] added the ability for transform procedure to operate on q…

### PR DESCRIPTION
**Pull request by guyd**
…ueries without dataset

### CODE REVIEW

**Comment by guyd** [comment]
The unrelated failing test is fixed in master.

**Comment by jeremybarnes** [comment]
This is a way to do INSERT INTO?

**Comment by nicolaskruchten** [comment]
Just lifting an arbitrary limitation which prevents simple test cases.

On Fri, Apr 1, 2016 at 11:11 PM, Jeremy Barnes <notifications@github.com>
wrote:

> This is a way to do INSERT INTO?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mldbai/mldb/pull/288#issuecomment-204636976>
>



-- 
Nicolas Kruchten, Eng  |  Staff Software Engineer at Datacratic  |
http://datacratic.com/

**Comment by nicolaskruchten** [comment]
can we get a +1 on this so we can merge? @steadtler @jeremybarnes

**Comment by steadtler** [comment]
+1

**Pull request merged**
