### PR TITLE
[MLDB-1691] Added str_length function

### PR DESCRIPTION
**Pull request by mailletf**

### CODE REVIEW

**Comment by steadtler** [comment]
pretty +1

**Comment by jeremybarnes** [comment]
@nicolaskruchten what is the function called in Postgres?

**Comment by nicolaskruchten** [comment]
it's called `char_length` in postgres. I suppose it would be best to follow suit.

**Comment by mailletf** [comment]
there's also a `length` function in postgres, that is a duplicate of `char_length` . I personally find `char_length` kind of odd

**Comment by nicolaskruchten** [comment]
Ok, length works for me

On Friday, 27 May 2016, François Maillet <notifications@github.com> wrote:

> there's also a length function in postgres, that is a duplicate of
> char_length . I personally find char_length kind of odd
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mldbai/mldb/pull/395#issuecomment-222249208>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAMbA_YSlOugSL-IRtDGyZNKKsL5YeZFks5qF1gAgaJpZM4IozCI>
> .
>


-- 
Nicolas Kruchten, Eng  |  Staff Software Engineer at Datacratic  |
http://datacratic.com/

**Pull request merged**
