### PR TITLE
Mldb 1559 fix transform

### PR DESCRIPTION
**Pull request by steadtler**
Fix the transform method of most sql expressions and document it.

### CODE REVIEW

**Comment by jeremybarnes** [comment]
You should probably merge the MLDB-1562 test in to this branch and make sure it fixes the issue on that testcase too.

**Comment by nicolaskruchten** [comment]
what's the status of this PR? mergable? work outstanding?

**Comment by steadtler** [comment]
whats the decision about the test functions?

On Mon, Apr 25, 2016 at 10:49 AM, Nicolas Kruchten <notifications@github.com

**Comment by nicolaskruchten** [comment]
I'm OK to merge the 1562 branch into this one and resolving both the issues if they're both fixed.

**Comment by steadtler** [comment]
I think 1562 is going to mess with the coords refactoring more, so I'll merge my fix and we'll see 1562 after the merge of the refactoring.

**Pull request merged**
