### PR TITLE
MLDBFB-443 temporal aggregator segfault test

### PR DESCRIPTION
**Pull request by FinchPowers**

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
+1

**Comment by FinchPowers** [comment]
@nicolaskruchten Si je merge ça les tests de MLDB ne passeront plus. Veux-tu que je merge quand même?

**Comment by nicolaskruchten** [comment]
Good point. We'll let @guyd merge the test once fixed :)

**Comment by jeremybarnes** [comment]
Tests should be merged directly into master, marked as manual IMO.  That way we don't have extra PR chatter.

**Comment by nicolaskruchten** [comment]
I've asked for this process so that I can validate that test cases (which
aren't always crashers) actually embody requirements we want to implement.

In this case we could indeed merge as manual.

On Fri, Apr 1, 2016 at 11:09 PM, Jeremy Barnes <notifications@github.com>
wrote:

> Tests should be merged directly into master, marked as manual IMO. That
> way we don't have extra PR chatter.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/mldbai/mldb/pull/291#issuecomment-204636890>
>



-- 
Nicolas Kruchten, Eng  |  Staff Software Engineer at Datacratic  |
http://datacratic.com/

**Comment by FinchPowers** [comment]
Merging it as manual would means "losing" the functional tests until the crashing one is fixed.

**Comment by nicolaskruchten** [comment]
Well, we could always move the crashed into its own test case

On Monday, 4 April 2016, Mich <notifications@github.com> wrote:

> Merging it as manual would means "losing" the functional tests until the
> crashing one is fixed.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/mldbai/mldb/pull/291#issuecomment-205252219>
>


-- 
Nicolas Kruchten, Eng  |  Staff Software Engineer at Datacratic  |
http://datacratic.com/

**Comment by guyd** [comment]
FYI - the test can be skipped directly in the python script with none of the problem described.

```
@unittest.skip('MLDBFB-433')
```

**Comment by FinchPowers** [comment]
@guyd Bon point. Je n'y avais pas pensé.

**Pull request merged**
