### PR TITLE
MLDB-1329 sql query memory leak

### PR DESCRIPTION
**Pull request by jeremybarnes**
This fixes the memory usage explosion running the pooling function (or sql.query).  It also addresses other performance issues discovered along the way.

Note that the root cause wasn't completely determined (it looks like some kind of circular reference between shared pointers), but this addresses the problem.

### CODE REVIEW

**Comment by guyd** [comment]
Is the commit 567f96b part of that PR?

**Comment by guyd** [comment]
Reviewed except for commit 567f96b.  +1

**Comment by jeremybarnes** [comment]
The extra commit made the test case much faster, which improved the iteration cycle.  It could be put into a separate PR but it's pretty low-risk.

**Comment by guyd** [comment]
Briefly reviewed 567f96b as well. +1

**Comment by jeremybarnes** [comment]
@nicolaskruchten @mailletf I'll let you merge this if and when you verify that it helps.

**Comment by mailletf** [comment]
I'm happy to confirm this fixes the issue on the POC2 data! Thanks for looking into it

**Pull request merged**
