### PR TITLE
MNIST demo notebook

### PR DESCRIPTION
**Pull request by jpilaul**

### CODE REVIEW

**Comment by guyd** [comment]
Overall this is an awesome demo.  There is one error when re-running this cell
screen shot 2016-08-19 at 2 22 26 pm
and I was not sure what's the purpose of the _offset_ field
screen shot 2016-08-19 at 2 28 13 pm

**Comment by guyd** [comment]
When loading the MNIST plugin I got a myriad of errors like these:
screen shot 2016-08-19 at 2 42 41 pm

**Comment by guyd** [comment]
May be the _Let's explore the data_ would be easier to understand if we were describing the dataset a bit and the column 785.

**Comment by guyd** [comment]
I would also try to reduce python code so that user attention is on MLDB code and not boilerplate code.  For example, in this cell:
screen shot 2016-08-19 at 3 06 47 pm

We can directly output MLDB response instead of drilling into it (as I've done).  Also, I am not sure why you are using a vertical_count here instead of the more common `count(*)`.

**Comment by jpilaul** [comment]
This is not the right version of the demo. I will need to resubmit my code. Sorry about that.

**Comment by guyd** [comment]
OK.  Let me know when you have it ready.

**Comment by jpilaul** [comment]
Ok - this is the correct version. I think that you were getting the errors occurred when you loaded the plugin because it needs the files from here:
https://github.com/mldbai/rt-mnist-digit-recogniser

**Comment by guyd** [comment]
Surprisingly the demo plugin does not seem as accurate as the training says it is.  For example, it get digit _7_ almost always wrong.

**Comment by guyd** [comment]
Also, the plugin UI could be more usable.  These are a few things that I felt were upsetting:
- picking from the mnist sample does not clear the drawing box resulting in digit overlays
- the results are show too far from the drawing box so it required scrolling all the time back and forth
- the main usage is draw and submit, therefore the two controls should next to each other.

Note that these are minor and I understand that this is a demo so people will not spent days in front of that screen.  Overall, I found the demo, especially the plugin, very fun and interactive.  Kudos.

**Comment by jpilaul** [comment]
Thanks again for the feedback!
7s are admittedly a little tough. Have you tried centering and resizing on 7s? The issue is that the user drawing will always be a little different from the train set so the "live prediction" may suffer as a result. To solve this issue, I have preprocessed the data and added centering and resizing option.

UI feedback makes a lot of sense - I will improve.

**Comment by guyd** [comment]
Regarding the failed predictions, this seems to happen as often with _7_ sampled from the mnist data.  This is why I thought there was something fishy.

**Comment by jpilaul** [comment]
Thanks for mentioning this. I think that I know what this is. I will submit a quick update on the plug-in to center based on pixel mass instead of box coordinates...

**Comment by mailletf** [comment]
MLDB's classifiers functions  et explain fucntions devraient pas avoir de S.

**Comment by mailletf** [comment]
A pickled version of the dataset is available on the deeplearning.net website http://deeplearning.net/tutorial/gettingstarted.html.
 -> mettre le lien sur le texte comme dans l'autre

**Comment by mailletf** [comment]
"In the original dataset, the labels were seperated." seperated in what? different files?

**Comment by mailletf** [comment]
pour le confusion matrix

```
pd.DataFrame(runResults["confusionMatrix"])\
    .pivot_table(index="actual", columns="predicted", fill_value=0)
```

qui vient d'ici: https://docs.mldb.ai/ipy/notebooks/_tutorials/_latest/Procedures%20and%20Functions%20Tutorial.html

**Comment by mailletf** [comment]
ajouter un "print" à cette ligne? mldb.put('/v1/functions/mnist_explainer', {

**Comment by mailletf** [comment]
"The explain function is called and outputs the weight of each pixels towards the final prediction." (qqchose comme)-> shows how helpful/hurtful each pixel was towards the final prediction. If it is red, it means the model thought it meant something that did not end up being true.

**Comment by mailletf** [comment]
"In the representation of the explain matrix (figure 3), the green pixels help increase the score while the red pixels help decrease the score of the chosen digit." même chose que commentaire précédent.

**Comment by mailletf** [comment]
"check out the on plugins" manque un . à la fin

**Comment by mailletf** [comment]
"      "address": "file:///mldb_data/do_you_knowwwwwzer_buster"" -> changer pour le link github quand on open source le plugin. il faudra décider si on veut nuker l'hsitorique ou non

**Comment by mailletf** [comment]
"/v1/plugins/my_pluginster" -> quelque chose d'autre? :P

**Comment by mailletf** [comment]
Dans le plugin:

- il manque un event javascript quand dessine qui trigger une prédiction quand on lache la souris. genre mouseup ou de quoi.
- les images qu'on peut clicker pour utiliser comme modèle ne sont pas la. as-tu oublié de les comiter? ou ?

**Comment by mailletf** [comment]
+1

**Pull request merged**
