### PR TITLE
ML::Thread_Specific -> thread_local (MLDB-1249)

### PR DESCRIPTION
**Pull request by jeremybarnes**
Since the current compilers aren't horrendously slow for thread_local, we can use it instead of the workaround.

### CODE REVIEW

**Comment by wsourdeau** [comment]
+1

**Comment by jeremybarnes** [comment]
@wsourdeau I deepened the changes; please re-check.

**Comment by jeremybarnes** [comment]
@jraby FYI once this patch lands, we'll no longer need boost-thread or boost-thread-dev to build or run MLDB.  We should update documentation and the Docker build.

**Comment by jeremybarnes** [comment]
Another spurious test failure...

**Pull request merged**
