### PR TITLE
sdk/sdk.mk: attempt to modify sdk_include_seed.cc under mldb/

### PR DESCRIPTION
**Pull request by wsourdeau**

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
does this work when compiling/building mldbpro?

**Comment by steadtler** [comment]
I'll allow it +1. (assuming you did compile everything)

**Comment by jeremybarnes** [comment]
Please verify that the files under build/x86_64/include/mldb/ are there after you make mldb_sdk, *without* an extra mldb/ in the path.

**Comment by wsourdeau** [comment]
@jeremybarnes Failed. Fixing...

**Comment by wsourdeau** [comment]
Merged.

**Pull request closed without merging**
