### PR TITLE
Mldb 1373 vertical horizontal latest

### PR DESCRIPTION
**Pull request by guyd**

### CODE REVIEW

**Comment by guyd** [comment]
This can be reviewed once PR 205 is merged.

**Comment by nicolaskruchten** [comment]
I can take care of the documentation of the new aggregators and aliases.

**Comment by guyd** [comment]
@nicolaskruchten That would be appreciated, especially if we want to release in the coming days.

**Comment by guyd** [comment]
This PR is obsolete.  A new PR will be created using the latest changes in master.

**Pull request closed without merging**
