### PR TITLE
changing default writeLevel of sparse.mutable MLDB-1339

### PR DESCRIPTION
**Pull request by nicolaskruchten**

### CODE REVIEW

**Comment by jeremybarnes** [comment]
I would add a big warning to the documentation saying that the default setting will look like it's losing data.

**Comment by nicolaskruchten** [comment]
Maybe I should rename the option consistencyLevel and the values
consistentAfterWrite vs consistentAfterCommit.

On Friday, 29 January 2016, Jeremy Barnes <notifications@github.com> wrote:

> I would add a big warning to the documentation saying that the default
> setting will look like it's losing data.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mldbai/mldb/pull/126#issuecomment-176998262>.
>


-- 
Nicolas Kruchten, Eng  |  Staff Software Engineer at Datacratic  |
http://datacratic.com/

**Comment by nicolaskruchten** [comment]
@jeremybarnes I added the warning, and changed the option names to be more suggestive of their impact.

**Comment by guyd** [comment]
+1

**Pull request merged**
