### PR TITLE
Edlib unit test integration

### PR DESCRIPTION
**Pull request by FinchPowers**
@jeremybarnes looks good or makes you sick? ;)

### CODE REVIEW

**Comment by mailletf** [comment]
do the test pass without the git-lfs files?

**Comment by FinchPowers** [comment]
Oui.

**Comment by jeremybarnes** [comment]
It doesn't make me sick, but I feel that unit testing of the libraries that we depend on is of very limited value.  I'm much rather we rewrite the unit tests as MLDB tests so that we exercise the interface... unless we're modifying the edlib code itself that is.

**Comment by FinchPowers** [comment]
Yes I'm going to modify edlib to support utf-8.

**Comment by jeremybarnes** [comment]
OK +1 then

**Pull request merged**
