### PR TITLE
MLDB-1058: restored in-house implementation of "trim"

### PR DESCRIPTION
**Pull request by wsourdeau**
Restored ML::trim, that was disabled without a bug report.

### CODE REVIEW

**Comment by FinchPowers** [comment]
Still brisé.

**Comment by wsourdeau** [comment]
Le test qui échoue n'est pas influencé par l'une ou l'autre des implémentations. C'est un hasard.

**Comment by jeremybarnes** [comment]
The reason it was disabled without a bug report was that it broke the SQL parsing (which needs the behavior to include stripping all characters including newlines), and so was reverted.  Until we understand what's going on there, we shouldn't change it back.

Also, in the case that there is no space at the beginning or end of a string, we should simply return a copy of the input string.  In the shared string implementation of our compiler, this is a significant performance gain.

**Comment by guyd** [comment]
@wsourdeau I created the JIRA to avoid any additional back-and-forth.  See https://datacratic.atlassian.net/browse/MLDB-1221.

**Comment by nicolaskruchten** [comment]
-1

I will create a test case to catch the regressions which caused this revert.

**Comment by wsourdeau** [comment]
@nicolaskruchten thanks!

**Comment by nicolaskruchten** [comment]
test case created and issue assigned

**Comment by wsourdeau** [comment]
@guyd all characters reported as spaces by "isspace" are now handled.

**Comment by wsourdeau** [comment]
@nicolaskruchten  all test cases pass now. The demos needs to be tested yet.

**Comment by guyd** [comment]
+1

**Comment by nicolaskruchten** [comment]
The demos can be tested by building a docker container, booting it, and then executing the notebooks through Jupyter. If the tests pass it should be fine though, so please merge when ready.

**Comment by wsourdeau** [comment]
(tests run 3 times, best result kept)
With fix: 80kqps
Without this fix: 75kqps
Gain: 5kqps

**Comment by nicolaskruchten** [comment]
you already have a +1, please merge :)

On Wed, Jan 13, 2016 at 3:05 PM, Wolfgang Sourdeau <notifications@github.com
> wrote:

> (tests run 3 times, best result kept)
> With fix: 80kqps
> Without this fix: 75kqps
> Gain: 5kqps
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mldbai/mldb/pull/41#issuecomment-171417111>.
>



-- 
Nicolas Kruchten, Eng  |  Staff Software Engineer at Datacratic  |
http://datacratic.com/

**Comment by wsourdeau** [comment]
Squash merged

**Pull request closed without merging**
