### PR TITLE
MLDB-1632 path optimizations

### PR DESCRIPTION
**Pull request by jeremybarnes**
This patch moves from a vector representation to an indexed string representation for paths.  It results in roughly a 2x speed improvement for query performance, due to less pointer chasing, and mostly closes the performance gap with the pre-singularity version of MLDB.

There are other improvements possible; this is the low-hanging fruit.

### CODE REVIEW

**Comment by steadtler** [comment]
+1

**Comment by nicolaskruchten** [comment]
@jeremybarnes the path_test fails in this branch...?

**Comment by jeremybarnes** [comment]
@nicolaskruchten it's valgrind being hyper-sensitive about some static initialization in jml.  I've taken it back out of that test for now.

**Comment by nicolaskruchten** [comment]
Wow, now there are 19 failures! :)

**Pull request merged**
