### PR TITLE
MLDB-1058: stopped logging stats uselessly until performance is improved

### PR DESCRIPTION
**Pull request by wsourdeau**
Those statistics are not being used currently and the mechanism in use harms the performance of the systme.

### CODE REVIEW

**Comment by jeremybarnes** [comment]
-1.  Let's put it behind a switch instead of removing it entirely.  In any case, it shouldn't cause much of a performance difference, does it?

**Comment by nicolaskruchten** [comment]
I vote to remove this: there are no users of this data and it seems trivial to add back in. AFAIK it does have a performance impact.

**Comment by nicolaskruchten** [comment]
@wsourdeau what is the performance improvement of this PR?

**Comment by wsourdeau** [comment]
@nicolaskruchten 11kqps

**Comment by nicolaskruchten** [comment]
@jeremybarnes thoughts?

**Comment by wsourdeau** [comment]
Btw, personally, I think the idea of a command-line switch is reasonable. However, I am willing to dig further in the understanding of why these simple function calls take so much cpu time. Since those are basically no-ops, they should take no time at all, presumably...

**Comment by jeremybarnes** [comment]
I would put it behind an if (false) {
}.  That way we can modify the condition to something that looks to see if anyone has registered a metrics handler, and have the metrics just work again.  For any production usage, we are going to want to keep them.

**Comment by wsourdeau** [comment]
@jeremybarnes done

**Comment by jeremybarnes** [comment]
+1

**Pull request merged**
